### ISSUE TITLE
Gorilla style compression

### ISSUE THREAD

**Issue by powturbo** [burmanm/gorilla-tsc#14]
You or the readers might have a look at the Gorilla style compression without inline assembly or SIMD. Full range 32/64 bits and better compression. More than 5 GB/s compression and more than 10 GB/s decompression. see: [TurboPFor Integer compression](https://github.com/powturbo/TurboPFor) including a ready to use benchmark application "icapp"

**Comment by burmanm** [comment]
Although I do like your project, it still faces two challenges: it's not Java and as such requires different compilation process (and deployment, QE, etc) and it's not available with an open license but a very restrictive copyleft one. Those two issues alone make it a target for different demographic than this one.

As this is not a real issue to the project I'm going to close it.

**Comment by powturbo** [comment]
ok, sorry. I've posted this after reading your excellent thesis, but not found your email.

**Comment by burmanm** [comment]
I don't like to share my private email address on public, but you can reach me from ``miburman at redhat.com``

I'd be interested to hear your thoughts (I'll read your fp.c meanwhile)
