### ISSUE TITLE
Incorrect Maven dependency

### ISSUE THREAD

**Issue by ambud** [burmanm/gorilla-tsc#6]
Dependency group id is incorrect in the README file, here's the correct one.

```xml
<dependency>
	<groupId>fi.iki.yak</groupId>
	<artifactId>compression-gorilla</artifactId>
	<version>1.1.0</version>
</dependency>
```

**Comment by burmanm** [comment]
Thanks, I'll fix the README with correct groupId (you can always find the newest dependency xml clip from the Maven repository logo also)
